INSERT INTO WEAPON (name, type, ammo) VALUES ('AKM', 'Assault', '7.62mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('FAMAS', 'Assault', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('FN SCAR', 'Assault', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('M16', 'Assault', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('SIG SG 550', 'Assault', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Steyr AUG', 'Assault', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('L85A1', 'Assault', '5.56mm')

INSERT INTO WEAPON (name, type, ammo) VALUES ('Colt M1911', 'Handgun', '.45 ACP')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Desert Eagle', 'Handgun', '.44 Magnum')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Luger pistol', 'Handgun', 9mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Glock 19', 'Handgun', '9mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Colt Anaconda', 'Handgun', '.44 Magnum')

INSERT INTO WEAPON (name, type, ammo) VALUES ('FN Minimi', 'LMG', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('HK123', 'LMG', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Vektor Mini-SS', 'LMG', '5.56mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Kk 62', 'LMG', '7.62mm')

INSERT INTO WEAPON (name, type, ammo) VALUES ('Kar98k', 'Rifle', '7.62mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('M1 Garand', 'Rifle', '7.62mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Mosin-Nagant', 'Rifle', '7.62mm')

INSERT INTO WEAPON (name, type, ammo) VALUES ('AA-12', 'Shotgun', '12 gauge')
INSERT INTO WEAPON (name, type, ammo) VALUES ('SPAS-12', 'Shotgun', '12 gauge')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Benelli M4', 'Shotgun', '12 gauge')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Winchester Model 1200', 'Shotgun', '12 gauge')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Remington Model 1100', 'Shotgun', '12 gauge')

INSERT INTO WEAPON (name, type, ammo) VALUES ('MP5', 'SMG', '9mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Vector', 'SMG', '9mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('MAC-10', 'SMG', '.45 ACP')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Tommy Gun', 'SMG', '.45 ACP')
INSERT INTO WEAPON (name, type, ammo) VALUES ('Uzi', 'SMG', '9mm')
INSERT INTO WEAPON (name, type, ammo) VALUES ('L2A3', 'SMG', '9mm')